### ISSUE TITLE
How to test model?

### ISSUE THREAD

**Issue by cn-actor** [sgawalsh/dqnTurtlebot#3]
Hello,I've trained it 1k episodes.How to test it？

**Comment by sgawalsh** [comment]
See my answer [here](https://github.com/sgawalsh/dqnTurtlebot/issues/4#issuecomment-642305541).

**Comment by cn-actor** [comment]
> See my answer [here](https://github.com/sgawalsh/dqnTurtlebot/issues/4#issuecomment-642305541).

Thx!
